language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq autoconf automake libmysqlclient-dev
install: ./install-dependencies.sh